::gulp
::gulp-util
::gulp-csslint
::gulp-jshint
::jshint-stylish
::gulp-plumber
::gulp-changed
::gulp-css-url-adjuster
::gulp-csso
::gulp-uglify
::gulp-imagemin
::gulp-sftp
::gulp-complexity
::opn
::gulp-jscs
::gulp-soften
::gulp-htmlhint
::run-sequence
::psi
::gulp-autoprefixer
::browser-sync
::gulp-removelogs
::gulp-load-plugins
::gulp-if
::gulp-size
::gulp-shell
::gulp-order
::gulp-concat
::yargs
::pageres
::main-bower-files
::require-dir
::gulp-tap
::penthouse
::gulp-devtools
::bower
::del
::gulp-eol
npm install -g gulp & npm install --save-dev gulp gulp-util gulp-csslint gulp-jshint jshint-stylish gulp-plumber gulp-changed gulp-css-url-adjuster gulp-csso gulp-uglify gulp-imagemin gulp-sftp gulp-complexity opn gulp-jscs gulp-soften gulp-htmlhint run-sequence psi gulp-autoprefixer browser-sync gulp-removelogs gulp-load-plugins gulp-if gulp-size gulp-shell gulp-order gulp-concat yargs pageres main-bower-files require-dir gulp-tap penthouse del gulp-eol & npm install -g gulp-devtools bower